### ISSUE TITLE
Compatibility with Spree 2.1

### ISSUE THREAD

**Issue by mbadov** [suryart/spree_active_sale#31]
Is this compatible with Spree 2.1?

Thanks for the great project!

**Comment by suryart** [comment]
Not yet, will be porting soon.

**Comment by mrkpatchaa** [comment]
I am working to modify the extension to make it compatible with latest version of spree.
I am getting an error related to nested scopes !

![spree_sales_error_3](https://cloud.githubusercontent.com/assets/1266755/2909548/286da872-d634-11e3-965c-324209d1002e.png)

**Comment by suryart** [comment]
Can you please mention the steps you followed to regenerate this issue?

Thanks.

On Thu, May 8, 2014 at 3:39 AM, Raymond Kpatchaa
notifications@github.comwrote:

> I am working to modify the extension to make it compatible with latest
> version of spree.
> I am getting an error related to nested scopes !
> 
> [image: spree_sales_error_3]https://cloud.githubusercontent.com/assets/1266755/2909548/286da872-d634-11e3-965c-324209d1002e.png
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/suryart/spree_active_sale/issues/31#issuecomment-42489805
> .

## 

Please consider the environment before printing this email.

Regards,
Surya

**Comment by mrkpatchaa** [comment]
Hi,
I have created a new repo of mine containing the code that I have in local now.
https://github.com/kraymond70/spree_active_sales

I have a readme file that could help you reproduice the bug.
If the bug is corrected i wish i could add some features (if needed) and I could push it to your repo.

**Comment by mrkpatchaa** [comment]
Hi, 
Please did you have time to check out my code ? Thanks

**Comment by BennyOnGit** [comment]
Hi Guys,

Is there any update on this?...is spree_active_sale compatible with the latest stable version of spree yet?  (I still get a lot of various dependency errors when trying to use...like the following):

Bundler could not find compatible versions for gem "railties":
  In Gemfile:
    sass-rails (~> 4.0.3) ruby depends on
      railties (< 5.0, >= 4.0.0) ruby

```
rails (= 3.2.8) ruby depends on
  railties (3.2.8)
```

appreciate it...

**Comment by dougjohnston** [comment]
Curious about this as well. Anyone using a variation of this gem with Spree 2.1+?

**Comment by mrkpatchaa** [comment]
No :( ! 
And as I am not as good in Ruby I couldn't do it on my own.

**Comment by mugoyal** [comment]
Is there any solution to this problem ? Bottleneck for me!!

**Comment by redglory** [comment]
I'm trying to adapt this gem to be compatible with 3-0-stable.
Dependencies are easy to overcome but I have to understand how to change all the attr_accessible to the controller params.require within STI logic.

**Comment by omkz** [comment]
could I see the code, @redglory ? I want to know how to upgrade the extension. do you have a tutorial? 
thank you
